export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const UPDATE_ROLE_USER_REQUEST = 'UPDATE_ROLE_USER_REQUEST';
export const UPDATE_ROLE_USER_SUCCESS = 'UPDATE_ROLE_USER_SUCCESS';
export const UPDATE_ROLE_USER_FAILURE = 'UPDATE_ROLE_USER_FAILURE';